<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Web._default" EnableEventValidation="false" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:UpdatePanel ID="upGridView" runat="server" UpdateMode="Conditional">
        <ContentTemplate>
             <br/>

            <asp:Label ID="lblName" runat="server" Text="姓名"></asp:Label>
            <asp:TextBox ID="txtName" runat="server"></asp:TextBox>
            <asp:Button ID="btnQuery" runat="server" OnClick="btnQuery_Click" Text="查詢"  BackColor="lightblue" BorderColor="White"/>
            <asp:Button ID="btnCreate" runat="server" Text="新增" OnClick="btnCreate_Click" BackColor="AliceBlue" BorderColor="White" />
           
            <br/>
             <br/>

            <asp:GridView ID="gvMaster" runat="server" AutoGenerateColumns="False"
                AutoGenerateSelectButton="True" Width="100%" DataKeyNames="SID,ID"
                OnSelectedIndexChanged="gvMaster_SelectedIndexChanged1" OnPageIndexChanging="gvMaster_PageIndexChanging"
                PageSize="3" OnPageIndexChanged="gvMaster_PageIndexChanged" OnRowDataBound="gvMaster_RowDataBound" BackColor="AliceBlue">
                <Columns>
                    <asp:BoundField  DataField="NO" HeaderText="編號" HeaderStyle-BackColor="lightblue" />
                    <asp:BoundField DataField="Id" HeaderText="ID" HeaderStyle-BackColor="lightblue" />
                    <asp:BoundField DataField="Name" HeaderText="姓名" HeaderStyle-BackColor="lightblue" />
                    <asp:TemplateField HeaderText="生日" HeaderStyle-BackColor="lightblue">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Birthday") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            (西年元)
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Birthday", "{0:yyy-MM-dd}") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="Age" HeaderText="年齡" HeaderStyle-BackColor="lightblue"/>

                </Columns>

            </asp:GridView>
            
    <br />
            <asp:Button ID="btnFirst" runat="server" Text="第一頁" CommandName="pageFirst" OnClick="gvMaster_PageIndexChanged" BackColor="AntiqueWhite" BorderStyle="None" />
            <asp:Button ID="btnPrev" runat="server" Text="上一頁" CommandName="pagePrev" OnClick="gvMaster_PageIndexChanged" BackColor="AntiqueWhite" BorderStyle="None" />
            <asp:Button ID="btnNext" runat="server" Text="下一頁" CommandName="pageNext" OnClick="gvMaster_PageIndexChanged" BackColor="AntiqueWhite" BorderStyle="None"/>
            <asp:Button ID="btnLast" runat="server" Text="最後頁" CommandName="pageLast" OnClick="gvMaster_PageIndexChanged" BackColor="AntiqueWhite" BorderStyle="None"/>
          
    <br />
            <%=DateTime.Now.ToString() %>
        </ContentTemplate>
    </asp:UpdatePanel>




    <br />

    <asp:UpdatePanel ID="upDetailsView" runat="server" UpdateMode="Conditional">
        <ContentTemplate>
            <asp:DetailsView ID="dvMaster" runat="server" Height="50px" Width="212px" OnModeChanging="dvMaster_ModeChanging" DataKeyNames="SID,ID" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
                AutoGenerateInsertButton="True" OnItemInserting="dvMaster_ItemInserting" 
                OnModeChanged="dvMaster_ModeChanged" AutoGenerateRows="False" OnItemUpdating="dvMaster_ItemUpdating" OnItemDeleting="dvMaster_ItemDeleting">
                <Fields>
                    <asp:BoundField DataField="NO" HeaderText="NO" HeaderStyle-BackColor="lightblue"/>
                    <asp:BoundField DataField="Name" HeaderText="姓名" HeaderStyle-BackColor="lightblue"/>
                    <asp:BoundField DataField="Address" HeaderText="Address" HeaderStyle-BackColor="lightblue"/>
                    <asp:BoundField DataField="Phone" HeaderText="Phone" HeaderStyle-BackColor="lightblue"/>
                    <asp:TemplateField HeaderText="Birthday" HeaderStyle-BackColor="lightblue">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Birthday") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <InsertItemTemplate>
                            <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Birthday", "{0:yyy-MM-dd}") %>'></asp:TextBox>
                        </InsertItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Bind("Birthday", "{0:yyy-MM-dd}") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Fields>
            </asp:DetailsView>           
    <br/>
            <%=DateTime.Now.ToString() %>
        </ContentTemplate>

    </asp:UpdatePanel>
      
    <br />

    <%--    //自訂樣式--%>
    <asp:UpdatePanel ID="upFormView" runat="server" UpdateMode="Conditional">
        <ContentTemplate>
            <asp:FormView ID="fvMaster" runat="server" Width="211px" DataKeyNames="SID,ID" Height="82px" OnItemInserting="fvMaster_ItemInserting" OnModeChanging="fvMaster_ModeChanging" OnItemDeleting="fvMaster_ItemDeleting" OnItemUpdating="fvMaster_ItemUpdating" OnDataBound="fvMaster_DataBound">
                <ItemTemplate>
                    <table>
                        <tbody>
                            <tr>
                                <td>
                                    <asp:Label ID="Label2" runat="server" Text="NO:"></asp:Label></td>
                                <td>

                                    <asp:Label ID="fvInserNo" runat="server" Text='<%# Eval("NO") %>'></asp:Label>

                                </td>
                                <td>


                                    <asp:Label ID="Label3" runat="server" Text="Name:"></asp:Label></td>
                                <td>
                                    <asp:Label ID="fvInsertName" runat="server" Text='<%# Eval("Name") %>'></asp:Label>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:Label ID="Label4" runat="server" Text="Address:"></asp:Label></td>
                                <td colspan="3">
                                    <asp:Label ID="TextBox2" runat="server" Text='<%# Eval("Address") %>' Width="100%"></asp:Label></td>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:Label ID="Label5" runat="server" Text="Phone:"></asp:Label></td>
                                <td>
                                    <asp:Label ID="TextBox3" runat="server" Text='<%# Eval("Phone") %>'></asp:Label>
                                </td>
                                <td>
                                    <asp:Label ID="Label6" runat="server" Text="Birthday:"></asp:Label></td>
                                <td>

                                    <asp:Label ID="fvMasterInsertBirthday" runat="server" Text='<%# Eval("Birthday") %>'></asp:Label>

                                </td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td></td>
                            </tr>
                        </tfoot>
                    </table>
                    <div>
                        <asp:Button ID="Button1" runat="server" Text="新增" CommandName="New" />
                        <asp:Button ID="btnCreate" runat="server" Text="編輯" CommandName="Edit" />
                        <asp:Button ID="btnCancel" runat="server" Text="刪除" CommandName="Delete" />
                    </div>
                </ItemTemplate>
                <EditItemTemplate>
                    <table>
                        <tbody>
                            <tr>
                                <td>
                                    <asp:Label ID="Label2" runat="server" Text="NO:"></asp:Label></td>
                                <td>
                                    <asp:TextBox ID="NO" runat="server" Text='<%# Bind("NO") %>'></asp:TextBox>

                                </td>
                                <td>
                                    <asp:Label ID="Label3" runat="server" Text="Name:"></asp:Label></td>
                                <td>
                                    <asp:TextBox ID="Name" runat="server" Text='<%# Bind("Name") %>'></asp:TextBox>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:Label ID="Label4" runat="server" Text="Address:"></asp:Label></td>
                                <td colspan="3">
                                    <%--<asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Address") %>' Width="100%"></asp:TextBox></td>--%>
                                        <asp:DropDownList ID="ddlAddress" runat="server" >
                                       <%-- <asp:ListItem Value="" Text="----請選擇------"></asp:ListItem>
                                          <asp:ListItem Value="1" Text="aaa"></asp:ListItem>
                                          <asp:ListItem Value="2" Text="bbb"></asp:ListItem>
                                          <asp:ListItem Value="3" Text="ccc"></asp:ListItem>--%>

                                    </asp:DropDownList>
                                       <ajaxToolkit:CascadingDropDown ID="cddAddress" runat="server" Enabled="True"
                                        ContextKey="" LoadingText="-- loading --" Category="address" PromptText="--請選擇---" ServicePath="~/WebServices/ajax.asmx"
                                        ServiceMethod="listAddress" UseContextKey="True" TargetControlID="ddlAddress" SelectedValue='<%# Bind("Address") %>'>
                                    </ajaxToolkit:CascadingDropDown>     
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:Label ID="Label5" runat="server" Text="Phone:"></asp:Label></td>
                                <td>
                                    <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("Phone") %>'></asp:TextBox>
                                </td>
                                <td>
                                    <asp:Label ID="Label6" runat="server" Text="Birthday:"></asp:Label></td>
                                <td>

                                    <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("Birthday") %>'></asp:TextBox>
                                </td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td></td>
                            </tr>
                        </tfoot>
                    </table>
                    <div>
                        <asp:Button ID="btnCreate" runat="server" Text="儲存" CommandName="Update" />
                        <asp:Button ID="btnCancel" runat="server" Text="取消" CommandName="Cancel" />
                    </div>
                </EditItemTemplate>
                <InsertItemTemplate>
                    <table>
                        <tbody>
                            <tr>
                                <td>
                                    <asp:Label ID="Label2" runat="server" Text="NO:"></asp:Label></td>
                                <td>
                                    <asp:TextBox ID="NO" runat="server" Text='<%# Bind("NO") %>'></asp:TextBox>

                                </td>
                                <td>
                                    <asp:Label ID="Label3" runat="server" Text="Name:"></asp:Label></td>
                                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="輸入名字" ControlToValidate="Name" ValidationGroup="vgFvMaster"></asp:RequiredFieldValidator>

                                <td>
                                    <asp:TextBox ID="Name" runat="server" Text='<%# Bind("Name") %>'></asp:TextBox>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:Label ID="Label4" runat="server" Text="Address:"></asp:Label></td>
                                <td colspan="3">
                                   <%--<asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Address") %>' Width="100%"></asp:TextBox></td>--%>
                                        <asp:DropDownList ID="ddlAddress" runat="server" >
                                       <%-- <asp:ListItem Value="" Text="----請選擇------"></asp:ListItem>
                                          <asp:ListItem Value="1" Text="aaa"></asp:ListItem>
                                          <asp:ListItem Value="2" Text="bbb"></asp:ListItem>
                                          <asp:ListItem Value="3" Text="ccc"></asp:ListItem>--%>

                                    </asp:DropDownList>
                                       <ajaxToolkit:CascadingDropDown ID="cddAddress" runat="server" Enabled="True"
                                        ContextKey="" LoadingText="-- loading --" Category="address" PromptText="--請選擇---" ServicePath="~/WebServices/ajax.asmx"
                                        ServiceMethod="listAddress" UseContextKey="True" TargetControlID="ddlAddress" SelectedValue='<%# Bind("Address") %>'>
                                    </ajaxToolkit:CascadingDropDown>     
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ErrorMessage="格是錯誤" ValidationExpression="((\d{10})|(((\(\d{2}\))|(\d{2}-))?\d{4}(-)?\d{3}(\d)?))" Display="Dynamic" ControlToValidate="TextBox3" ValidationGroup="vgFvMaster"></asp:RegularExpressionValidator>

                                    <asp:Label ID="Label5" runat="server" Text="Phone:"></asp:Label></td>
                                <td>
                                    <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("Phone") %>'></asp:TextBox>
                                </td>
                                <td>
                                    <asp:Label ID="Label6" runat="server" Text="Birthday:"></asp:Label></td>
                                <td>
                                    <ajaxToolkit:CalendarExtender ID="CalendarExtender1" runat="server" TargetControlID="TextBox4" />
                                    <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("Birthday") %>'></asp:TextBox>
                                </td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td></td>
                            </tr>
                        </tfoot>
                    </table>
                    <asp:CustomValidator ID="CustomValidator1" runat="server" OnServerValidate="CustomValidator1_ServerValidate" ControlToValidate="NO" ValidationGroup="vgFvMaster" ValidateEmptyText="true"></asp:CustomValidator>
                    <br/>
                    <div>
                        <asp:Button ID="btnCreate" runat="server" Text="建立" CommandName="Insert" ValidationGroup="vgFvMaster"  BackColor="AntiqueWhite" BorderStyle="None"  />
                        <asp:Button ID="btnCancel" runat="server" Text="取消" CommandName="Cancel"  BackColor="AntiqueWhite" BorderStyle="None"  />
                    </div>
                </InsertItemTemplate>
            </asp:FormView>
            <%=DateTime.Now.ToString() %>
        </ContentTemplate>

        <Triggers>
            <asp:AsyncPostBackTrigger ControlID="btnCreate" />
        </Triggers>

    </asp:UpdatePanel>




</asp:Content>
